FROM node:22.15.0-alpine AS builder

WORKDIR /build

COPY package*.json tsconfig.json ./
COPY packages ./packages

RUN npm ci

RUN npm run monolith.build.yandex.serverless

FROM node:22.15.0-alpine AS production

WORKDIR /app

COPY --from=builder /build/packages/monolith/dist ./dist

EXPOSE 3000

CMD ["node", "./dist/index.cjs"]