services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.monolith.develop
    container_name: analytics-app
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - analytics-network
    depends_on:
      - mongodb
    volumes:
      - ./packages:/app/packages
      - ./tsconfig.json:/app/tsconfig.json
    environment:
      CHOKIDAR_USEPOLLING: true
      CHOKIDAR_INTERVAL: 1000
  mongodb:
    image: mongo:8.0.10-noble
    container_name: analytics-mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    networks:
      - analytics-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    networks:
      - analytics-network
    depends_on:
      - mongodb

networks:
  analytics-network:
    driver: bridge
    name: monolith_network
