FROM golang:1.24 as builder
WORKDIR /app
RUN go install go.k6.io/xk6@latest
RUN xk6 build --with github.com/grafana/xk6-output-influxdb

FROM alpine
COPY --from=builder /app/k6 /usr/local/bin/k6
ENTRYPOINT ["k6"]