FROM node:22.15.0-alpine AS development

WORKDIR /app

COPY package*.json tsconfig.json ./
COPY packages ./packages

RUN npm ci

EXPOSE 3000

VOLUME ["/app/packages"]

CMD ["npm", "run", "monolith.develop"]